"""
Prometheus metrics for PhytRAG.

All metric objects are module-level singletons so any module can import
and increment them without passing instances around.

Registered metrics:
  phytrag_queries_total          - counter, labelled by status (ok/error)
  phytrag_query_latency_seconds  - histogram, end-to-end query time
  phytrag_ttft_seconds           - histogram, time to first token
  phytrag_tokens_generated_total - counter, total LLM output tokens
  phytrag_retrieval_score        - histogram, cosine similarity of retrieved chunks
  phytrag_errors_total           - counter, labelled by pipeline stage

These feed the Grafana dashboards provisioned in grafana/dashboards/.
"""
from fastapi import FastAPI
from prometheus_client import Counter, Histogram, make_asgi_app

# ── Metric definitions ────────────────────────────────────────────────────────

QUERY_COUNTER = Counter(
    "phytrag_queries_total",
    "Total number of queries handled",
    ["status"],  # ok | error
)

QUERY_LATENCY = Histogram(
    "phytrag_query_latency_seconds",
    "End-to-end query latency in seconds",
    ["status"],
    buckets=[0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0, 30.0, 60.0],
)

TTFT_HISTOGRAM = Histogram(
    "phytrag_ttft_seconds",
    "Time to first token from LLM in seconds",
    buckets=[0.2, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0],
)

TOKENS_COUNTER = Counter(
    "phytrag_tokens_generated_total",
    "Total number of tokens generated by the LLM",
)

RETRIEVAL_SCORE = Histogram(
    "phytrag_retrieval_score",
    "Cosine similarity score of retrieved chunks",
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
)

ERROR_COUNTER = Counter(
    "phytrag_errors_total",
    "Total errors by pipeline stage",
    ["stage"],  # embed | retrieve | generate | query
)


# ── Prometheus ASGI mount ─────────────────────────────────────────────────────

def setup_metrics(app: FastAPI) -> None:
    """
    Mount the Prometheus metrics endpoint at /metrics.
    Prometheus scrapes this every 15s (configured in prometheus.yml).
    """
    metrics_app = make_asgi_app()
    app.mount("/metrics", metrics_app)
